//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Hotline.ServicesWeb.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WS_Hotline.ServicesWeb.Ressources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achats.
        /// </summary>
        internal static string Achats {
            get {
                return ResourceManager.GetString("Achats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher uniquement les lignes sélectionnées.
        /// </summary>
        internal static string AfficherPiecesSelec {
            get {
                return ResourceManager.GetString("AfficherPiecesSelec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        internal static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ici le message erreur est affiché!.
        /// </summary>
        internal static string BodyPopupErreur {
            get {
                return ResourceManager.GetString("BodyPopupErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        internal static string BuNext {
            get {
                return ResourceManager.GetString("BuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de selectionner un dossier.
        /// </summary>
        internal static string BuNextTooltip {
            get {
                return ResourceManager.GetString("BuNextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différence.
        /// </summary>
        internal static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combinaison login / mot de passe incorrecte.
        /// </summary>
        internal static string ErreurConnexion {
            get {
                return ResourceManager.GetString("ErreurConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun dossier sélectionné.
        /// </summary>
        internal static string ErreurDossier {
            get {
                return ResourceManager.GetString("ErreurDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie n&apos;est pas numérique.
        /// </summary>
        internal static string ErreurIsNumerique {
            get {
                return ResourceManager.GetString("ErreurIsNumerique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur saisie doit être inferieure ou égale au montant à imputer.
        /// </summary>
        internal static string ErreurIsSuperieur {
            get {
                return ResourceManager.GetString("ErreurIsSuperieur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtre :.
        /// </summary>
        internal static string Filtre {
            get {
                return ResourceManager.GetString("Filtre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection des dossiers.
        /// </summary>
        internal static string GestDossier {
            get {
                return ResourceManager.GetString("GestDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner le dossier sur lequel vous souhaitez travailler..
        /// </summary>
        internal static string InfoSelectionDossier {
            get {
                return ResourceManager.GetString("InfoSelectionDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achat.
        /// </summary>
        internal static string LabelAchat {
            get {
                return ResourceManager.GetString("LabelAchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string LabelAction {
            get {
                return ResourceManager.GetString("LabelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analytique.
        /// </summary>
        internal static string LabelAnalytique {
            get {
                return ResourceManager.GetString("LabelAnalytique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string LabelAnnuler {
            get {
                return ResourceManager.GetString("LabelAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Associations disponibles.
        /// </summary>
        internal static string LabelAssociations {
            get {
                return ResourceManager.GetString("LabelAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À transferer.
        /// </summary>
        internal static string LabelATransferer {
            get {
                return ResourceManager.GetString("LabelATransferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun Dossier.
        /// </summary>
        internal static string LabelAucunDossier {
            get {
                return ResourceManager.GetString("LabelAucunDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le réglement XXX va être supprimé..
        /// </summary>
        internal static string LabelAvertBodyReg {
            get {
                return ResourceManager.GetString("LabelAvertBodyReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avertissement.
        /// </summary>
        internal static string LabelAvertTitle {
            get {
                return ResourceManager.GetString("LabelAvertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avoir.
        /// </summary>
        internal static string LabelAvoir {
            get {
                return ResourceManager.GetString("LabelAvoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Banque.
        /// </summary>
        internal static string LabelBanque {
            get {
                return ResourceManager.GetString("LabelBanque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string LabelBtnConnexion {
            get {
                return ResourceManager.GetString("LabelBtnConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte Cador.
        /// </summary>
        internal static string LabelCompteCador {
            get {
                return ResourceManager.GetString("LabelCompteCador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez contacter votre administrateur.
        /// </summary>
        internal static string LabelContactAdmin {
            get {
                return ResourceManager.GetString("LabelContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte de contrepartie.
        /// </summary>
        internal static string LabelContrepartie {
            get {
                return ResourceManager.GetString("LabelContrepartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;échéance de la facture.
        /// </summary>
        internal static string LabelDateEcheanceFacture {
            get {
                return ResourceManager.GetString("LabelDateEcheanceFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de la facture.
        /// </summary>
        internal static string LabelDateFacture {
            get {
                return ResourceManager.GetString("LabelDateFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de la pièce.
        /// </summary>
        internal static string LabelDateListePieces {
            get {
                return ResourceManager.GetString("LabelDateListePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string LabelDateReg {
            get {
                return ResourceManager.GetString("LabelDateReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déséquilibrée.
        /// </summary>
        internal static string LabelDesequilibre {
            get {
                return ResourceManager.GetString("LabelDesequilibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element 4.
        /// </summary>
        internal static string LabelElem4 {
            get {
                return ResourceManager.GetString("LabelElem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element 5.
        /// </summary>
        internal static string LabelElem5 {
            get {
                return ResourceManager.GetString("LabelElem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element 6.
        /// </summary>
        internal static string LabelElem6 {
            get {
                return ResourceManager.GetString("LabelElem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner un dossier.
        /// </summary>
        internal static string LabelErreurBody {
            get {
                return ResourceManager.GetString("LabelErreurBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner un réglement.
        /// </summary>
        internal static string LabelErreurBodyReg {
            get {
                return ResourceManager.GetString("LabelErreurBodyReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string LabelErreurTitle {
            get {
                return ResourceManager.GetString("LabelErreurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facture.
        /// </summary>
        internal static string LabelFacture {
            get {
                return ResourceManager.GetString("LabelFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du tiers.
        /// </summary>
        internal static string LabelFournisseur {
            get {
                return ResourceManager.GetString("LabelFournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tiers.
        /// </summary>
        internal static string LabelFournisseurListePieces {
            get {
                return ResourceManager.GetString("LabelFournisseurListePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HT.
        /// </summary>
        internal static string LabelHT {
            get {
                return ResourceManager.GetString("LabelHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez préciser si il s&apos;agit d&apos;une facture fournisseur ou d&apos;un avoir fournisseur.
        /// </summary>
        internal static string LabelInformationChoixTypePiece {
            get {
                return ResourceManager.GetString("LabelInformationChoixTypePiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des pièces déjà saisies.
        /// </summary>
        internal static string LabelInformationListePieces {
            get {
                return ResourceManager.GetString("LabelInformationListePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé.
        /// </summary>
        internal static string LabelLibelle {
            get {
                return ResourceManager.GetString("LabelLibelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode de Règlement.
        /// </summary>
        internal static string LabelModeReg {
            get {
                return ResourceManager.GetString("LabelModeReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module d&apos;achat.
        /// </summary>
        internal static string LabelModuleAchat {
            get {
                return ResourceManager.GetString("LabelModuleAchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module de vente.
        /// </summary>
        internal static string LabelModuleVente {
            get {
                return ResourceManager.GetString("LabelModuleVente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant de la pièce.
        /// </summary>
        internal static string LabelMontantPiece {
            get {
                return ResourceManager.GetString("LabelMontantPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant.
        /// </summary>
        internal static string LabelMontantReg {
            get {
                return ResourceManager.GetString("LabelMontantReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant réglé.
        /// </summary>
        internal static string LabelMontantRegle {
            get {
                return ResourceManager.GetString("LabelMontantRegle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant TTC.
        /// </summary>
        internal static string LabelMontantTTC {
            get {
                return ResourceManager.GetString("LabelMontantTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant TTC.
        /// </summary>
        internal static string LabelMontantttcListePieces {
            get {
                return ResourceManager.GetString("LabelMontantttcListePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant TTC de la pièce.
        /// </summary>
        internal static string LabelMontantTtcPiece {
            get {
                return ResourceManager.GetString("LabelMontantTtcPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant TVA.
        /// </summary>
        internal static string LabelMontantTVA {
            get {
                return ResourceManager.GetString("LabelMontantTVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom Tiers.
        /// </summary>
        internal static string LabelNomReg {
            get {
                return ResourceManager.GetString("LabelNomReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle pièce.
        /// </summary>
        internal static string LabelNouvellePiece {
            get {
                return ResourceManager.GetString("LabelNouvellePiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro.
        /// </summary>
        internal static string LabelNumero {
            get {
                return ResourceManager.GetString("LabelNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de Chrono de la facture.
        /// </summary>
        internal static string LabelNumeroChrono {
            get {
                return ResourceManager.GetString("LabelNumeroChrono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de la pièce.
        /// </summary>
        internal static string LabelNumeroPiece {
            get {
                return ResourceManager.GetString("LabelNumeroPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nº.
        /// </summary>
        internal static string LabelNumReg {
            get {
                return ResourceManager.GetString("LabelNumReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ou.
        /// </summary>
        internal static string LabelOu {
            get {
                return ResourceManager.GetString("LabelOu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La pièce est équilibrée.
        /// </summary>
        internal static string LabelPieceEquilibre {
            get {
                return ResourceManager.GetString("LabelPieceEquilibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur!.
        /// </summary>
        internal static string LabelPopupErreur {
            get {
                return ResourceManager.GetString("LabelPopupErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter le module.
        /// </summary>
        internal static string LabelQuitterModule {
            get {
                return ResourceManager.GetString("LabelQuitterModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référence fournisseur.
        /// </summary>
        internal static string LabelReferenceFournisseur {
            get {
                return ResourceManager.GetString("LabelReferenceFournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez reporter le numéro sur votre pièce.
        /// </summary>
        internal static string LabelReporterNumPiece {
            get {
                return ResourceManager.GetString("LabelReporterNumPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisie d&apos;une pièce d&apos;achat.
        /// </summary>
        internal static string LabelSaisieAchat {
            get {
                return ResourceManager.GetString("LabelSaisieAchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisie d&apos;une pièce de vente.
        /// </summary>
        internal static string LabelSaisieVente {
            get {
                return ResourceManager.GetString("LabelSaisieVente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le montant TTC.
        /// </summary>
        internal static string LabelSaisirMontantTTC {
            get {
                return ResourceManager.GetString("LabelSaisirMontantTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner.
        /// </summary>
        internal static string LabelSelectionner {
            get {
                return ResourceManager.GetString("LabelSelectionner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        internal static string LabelStatusListePieces {
            get {
                return ResourceManager.GetString("LabelStatusListePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transferer.
        /// </summary>
        internal static string LabelTransferer {
            get {
                return ResourceManager.GetString("LabelTransferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trésorerie.
        /// </summary>
        internal static string LabelTresorerie {
            get {
                return ResourceManager.GetString("LabelTresorerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant TTC.
        /// </summary>
        internal static string LabelTTC {
            get {
                return ResourceManager.GetString("LabelTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux TVA.
        /// </summary>
        internal static string LabelTVA {
            get {
                return ResourceManager.GetString("LabelTVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de dépense.
        /// </summary>
        internal static string LabelTypeDepense {
            get {
                return ResourceManager.GetString("LabelTypeDepense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type pièce.
        /// </summary>
        internal static string LabelTypeListePieces {
            get {
                return ResourceManager.GetString("LabelTypeListePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de mouvement.
        /// </summary>
        internal static string LabelTypeMvt {
            get {
                return ResourceManager.GetString("LabelTypeMvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de saisie.
        /// </summary>
        internal static string LabelTypeSaisie {
            get {
                return ResourceManager.GetString("LabelTypeSaisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de saisie.
        /// </summary>
        internal static string LabelTypeSaisieTitle {
            get {
                return ResourceManager.GetString("LabelTypeSaisieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de tiers.
        /// </summary>
        internal static string LabelTypeTiers {
            get {
                return ResourceManager.GetString("LabelTypeTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le montant HT doit être supérieur à 0.
        /// </summary>
        internal static string LabelVerifHT {
            get {
                return ResourceManager.GetString("LabelVerifHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un achat.
        /// </summary>
        internal static string LegendeAchat {
            get {
                return ResourceManager.GetString("LegendeAchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un règlement.
        /// </summary>
        internal static string LegendeReglement {
            get {
                return ResourceManager.GetString("LegendeReglement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir une vente.
        /// </summary>
        internal static string LegendeVente {
            get {
                return ResourceManager.GetString("LegendeVente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analytique.
        /// </summary>
        internal static string LibelleAnalytique {
            get {
                return ResourceManager.GetString("LibelleAnalytique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question(s).
        /// </summary>
        internal static string LibelleColQuestion {
            get {
                return ResourceManager.GetString("LibelleColQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de dépense.
        /// </summary>
        internal static string LibelleCompteG {
            get {
                return ResourceManager.GetString("LibelleCompteG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant.
        /// </summary>
        internal static string Montant {
            get {
                return ResourceManager.GetString("Montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indiquer le montant à imputer.
        /// </summary>
        internal static string MontantImputer {
            get {
                return ResourceManager.GetString("MontantImputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant restant à régler .
        /// </summary>
        internal static string MontantRestant {
            get {
                return ResourceManager.GetString("MontantRestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string NomDossier {
            get {
                return ResourceManager.GetString("NomDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parametrage.
        /// </summary>
        internal static string Parametrage {
            get {
                return ResourceManager.GetString("Parametrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        internal static string Quitter {
            get {
                return ResourceManager.GetString("Quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réglements.
        /// </summary>
        internal static string Reglements {
            get {
                return ResourceManager.GetString("Reglements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse(s).
        /// </summary>
        internal static string ReponseColQuestion {
            get {
                return ResourceManager.GetString("ReponseColQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restant.
        /// </summary>
        internal static string Restant {
            get {
                return ResourceManager.GetString("Restant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionné.
        /// </summary>
        internal static string Selectionne {
            get {
                return ResourceManager.GetString("Selectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solde restant :.
        /// </summary>
        internal static string SoldeRestant {
            get {
                return ResourceManager.GetString("SoldeRestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue sur votre logiciel de Saisie Comptable Assistée.
        /// </summary>
        internal static string SousTitreSCA {
            get {
                return ResourceManager.GetString("SousTitreSCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Masquer au démarrage.
        /// </summary>
        internal static string TextCheckBox {
            get {
                return ResourceManager.GetString("TextCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner la première ligne dépense de votre facture :.
        /// </summary>
        internal static string TitleCompteG {
            get {
                return ResourceManager.GetString("TitleCompteG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dossier.
        /// </summary>
        internal static string TitleDossier {
            get {
                return ResourceManager.GetString("TitleDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection de réglements.
        /// </summary>
        internal static string TitleListeReg {
            get {
                return ResourceManager.GetString("TitleListeReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun question a été trouvé pour ce compte!.
        /// </summary>
        internal static string TitlePasQuestion {
            get {
                return ResourceManager.GetString("TitlePasQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module de Question.
        /// </summary>
        internal static string TitlePopUpQues {
            get {
                return ResourceManager.GetString("TitlePopUpQues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de répondre aux questions ci-dessous :.
        /// </summary>
        internal static string TitleQuestion {
            get {
                return ResourceManager.GetString("TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentification.
        /// </summary>
        internal static string TitreAuthentification {
            get {
                return ResourceManager.GetString("TitreAuthentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des factures / avoirs sélectionnés.
        /// </summary>
        internal static string TitreListe {
            get {
                return ResourceManager.GetString("TitreListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisie du montant de la facture .
        /// </summary>
        internal static string TitreMontantImputation {
            get {
                return ResourceManager.GetString("TitreMontantImputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner une facture.
        /// </summary>
        internal static string TitreSelectionFacture {
            get {
                return ResourceManager.GetString("TitreSelectionFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner une pièce.
        /// </summary>
        internal static string TitreSelectionPiece {
            get {
                return ResourceManager.GetString("TitreSelectionPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deconnexion.
        /// </summary>
        internal static string ToolTipLogout {
            get {
                return ResourceManager.GetString("ToolTipLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail à envoyer?.
        /// </summary>
        internal static string ToolTipMail {
            get {
                return ResourceManager.GetString("ToolTipMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Besoin d&apos;aide?.
        /// </summary>
        internal static string ToolTipQuestion {
            get {
                return ResourceManager.GetString("ToolTipQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total des avoirs séléctionnés :.
        /// </summary>
        internal static string TotalAvoirs {
            get {
                return ResourceManager.GetString("TotalAvoirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total des montants imputés :.
        /// </summary>
        internal static string TotalMontants {
            get {
                return ResourceManager.GetString("TotalMontants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total du règlement : .
        /// </summary>
        internal static string TotalReglement {
            get {
                return ResourceManager.GetString("TotalReglement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes.
        /// </summary>
        internal static string Ventes {
            get {
                return ResourceManager.GetString("Ventes", resourceCulture);
            }
        }
    }
}
