 
 
 

 







 
 





// Generated helper templates
// Generated items
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\User\CritereUserDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\User\UserDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\UserController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\User\UserMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\User\UserMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\User\UserDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\User\UserDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\User\UserConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\UserException\UserException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\User\CritereUserDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\User\UserDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Views\Dossier\CritereDossierDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Views\Dossier\DossierDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\DossierController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Dossier\DossierMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Dossier\DossierMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Dossier\DossierDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Dossier\DossierDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Dossier\DossierConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\DossierException\DossierException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Dossier\CritereDossierDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Dossier\DossierDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Version\CritereVersionDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Version\VersionDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\VersionController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Version\VersionMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Version\VersionMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Version\VersionDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Version\VersionDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Version\VersionConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\VersionException\VersionException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Version\CritereVersionDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Version\VersionDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\User\CritereUserDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\User\UserDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\UserController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\User\UserMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\User\UserMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\User\UserDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\User\UserDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\User\UserConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\UserException\UserException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\User\CritereUserDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\User\UserDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TypeTiers\CritereTypeTiersDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TypeTiers\TypeTiersDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\TypeTiersController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\TypeTiers\TypeTiersMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\TypeTiers\TypeTiersMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\TypeTiers\TypeTiersDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TypeTiers\TypeTiersDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TypeTiers\TypeTiersConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\TypeTiersException\TypeTiersException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TypeTiers\CritereTypeTiersDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TypeTiers\TypeTiersDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TypeSaisie\CritereTypeSaisieDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TypeSaisie\TypeSaisieDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\TypeSaisieController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\TypeSaisie\TypeSaisieMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\TypeSaisie\TypeSaisieMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\TypeSaisie\TypeSaisieDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TypeSaisie\TypeSaisieDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TypeSaisie\TypeSaisieConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\TypeSaisieException\TypeSaisieException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TypeSaisie\CritereTypeSaisieDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TypeSaisie\TypeSaisieDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TypeMouvement\CritereTypeMouvementDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TypeMouvement\TypeMouvementDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\TypeMouvementController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\TypeMouvement\TypeMouvementMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\TypeMouvement\TypeMouvementMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\TypeMouvement\TypeMouvementDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TypeMouvement\TypeMouvementDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TypeMouvement\TypeMouvementConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\TypeMouvementException\TypeMouvementException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TypeMouvement\CritereTypeMouvementDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TypeMouvement\TypeMouvementDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Tva\CritereTvaDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Tva\TvaDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\TvaController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Tva\TvaMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Tva\TvaMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Tva\TvaDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Tva\TvaDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Tva\TvaConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\TvaException\TvaException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Tva\CritereTvaDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Tva\TvaDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TiersCompte\CritereTiersCompteDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\TiersCompte\TiersCompteDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\TiersCompteController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\TiersCompte\TiersCompteMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\TiersCompte\TiersCompteMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\TiersCompte\TiersCompteDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TiersCompte\TiersCompteDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\TiersCompte\TiersCompteConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\TiersCompteException\TiersCompteException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TiersCompte\CritereTiersCompteDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\TiersCompte\TiersCompteDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Tiers\CritereTiersDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Tiers\TiersDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\TiersController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Tiers\TiersMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Tiers\TiersMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Tiers\TiersDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Tiers\TiersDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Tiers\TiersConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\TiersException\TiersException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Tiers\CritereTiersDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Tiers\TiersDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Softlog\CritereSoftlogDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Softlog\SoftlogDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\SoftlogController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Softlog\SoftlogMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Softlog\SoftlogMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Softlog\SoftlogDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Softlog\SoftlogDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Softlog\SoftlogConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\SoftlogException\SoftlogException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Softlog\CritereSoftlogDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Softlog\SoftlogDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Reponse\CritereReponseDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Reponse\ReponseDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ReponseController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Reponse\ReponseMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Reponse\ReponseMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Reponse\ReponseDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Reponse\ReponseDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Reponse\ReponseConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ReponseException\ReponseException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Reponse\CritereReponseDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Reponse\ReponseDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ReglementPiece\CritereReglementPieceDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ReglementPiece\ReglementPieceDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ReglementPieceController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\ReglementPiece\ReglementPieceMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\ReglementPiece\ReglementPieceMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\ReglementPiece\ReglementPieceDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ReglementPiece\ReglementPieceDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ReglementPiece\ReglementPieceConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ReglementPieceException\ReglementPieceException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ReglementPiece\CritereReglementPieceDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ReglementPiece\ReglementPieceDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Reglement\CritereReglementDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Reglement\ReglementDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ReglementController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Reglement\ReglementMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Reglement\ReglementMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Reglement\ReglementDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Reglement\ReglementDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Reglement\ReglementConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ReglementException\ReglementException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Reglement\CritereReglementDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Reglement\ReglementDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\RacineTiers\CritereRacineTiersDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\RacineTiers\RacineTiersDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\RacineTiersController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\RacineTiers\RacineTiersMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\RacineTiers\RacineTiersMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\RacineTiers\RacineTiersDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\RacineTiers\RacineTiersDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\RacineTiers\RacineTiersConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\RacineTiersException\RacineTiersException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\RacineTiers\CritereRacineTiersDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\RacineTiers\RacineTiersDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ParamUnite\CritereParamUniteDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ParamUnite\ParamUniteDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ParamUniteController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\ParamUnite\ParamUniteMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\ParamUnite\ParamUniteMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\ParamUnite\ParamUniteDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ParamUnite\ParamUniteDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ParamUnite\ParamUniteConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ParamUniteException\ParamUniteException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ParamUnite\CritereParamUniteDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ParamUnite\ParamUniteDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ParamQuestionListe\CritereParamQuestionListeDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ParamQuestionListe\ParamQuestionListeDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ParamQuestionListeController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\ParamQuestionListe\ParamQuestionListeMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\ParamQuestionListe\ParamQuestionListeMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\ParamQuestionListe\ParamQuestionListeDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ParamQuestionListe\ParamQuestionListeDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ParamQuestionListe\ParamQuestionListeConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ParamQuestionListeException\ParamQuestionListeException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ParamQuestionListe\CritereParamQuestionListeDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ParamQuestionListe\ParamQuestionListeDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ParamQuestion\CritereParamQuestionDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ParamQuestion\ParamQuestionDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ParamQuestionController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\ParamQuestion\ParamQuestionMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\ParamQuestion\ParamQuestionMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\ParamQuestion\ParamQuestionDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ParamQuestion\ParamQuestionDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ParamQuestion\ParamQuestionConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ParamQuestionException\ParamQuestionException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ParamQuestion\CritereParamQuestionDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ParamQuestion\ParamQuestionDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Module\CritereModuleDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Module\ModuleDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ModuleController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Module\ModuleMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Module\ModuleMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Module\ModuleDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Module\ModuleDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Module\ModuleConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ModuleException\ModuleException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Module\CritereModuleDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Module\ModuleDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ModeReglement\CritereModeReglementDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\ModeReglement\ModeReglementDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ModeReglementController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\ModeReglement\ModeReglementMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\ModeReglement\ModeReglementMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\ModeReglement\ModeReglementDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ModeReglement\ModeReglementDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\ModeReglement\ModeReglementConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ModeReglementException\ModeReglementException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ModeReglement\CritereModeReglementDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\ModeReglement\ModeReglementDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\LiaiUniteModule\CritereLiaiUniteModuleDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\LiaiUniteModule\LiaiUniteModuleDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\LiaiUniteModuleController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\LiaiUniteModule\LiaiUniteModuleMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\LiaiUniteModule\LiaiUniteModuleMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\LiaiUniteModule\LiaiUniteModuleDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\LiaiUniteModule\LiaiUniteModuleDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\LiaiUniteModule\LiaiUniteModuleConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\LiaiUniteModuleException\LiaiUniteModuleException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\LiaiUniteModule\CritereLiaiUniteModuleDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\LiaiUniteModule\LiaiUniteModuleDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\LiaiAgentModule\CritereLiaiAgentModuleDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\LiaiAgentModule\LiaiAgentModuleDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\LiaiAgentModuleController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\LiaiAgentModule\LiaiAgentModuleMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\LiaiAgentModule\LiaiAgentModuleMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\LiaiAgentModule\LiaiAgentModuleDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\LiaiAgentModule\LiaiAgentModuleDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\LiaiAgentModule\LiaiAgentModuleConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\LiaiAgentModuleException\LiaiAgentModuleException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\LiaiAgentModule\CritereLiaiAgentModuleDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\LiaiAgentModule\LiaiAgentModuleDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\EtapeSaisie\CritereEtapeSaisieDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\EtapeSaisie\EtapeSaisieDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\EtapeSaisieController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\EtapeSaisie\EtapeSaisieMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\EtapeSaisie\EtapeSaisieMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\EtapeSaisie\EtapeSaisieDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\EtapeSaisie\EtapeSaisieDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\EtapeSaisie\EtapeSaisieConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\EtapeSaisieException\EtapeSaisieException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\EtapeSaisie\CritereEtapeSaisieDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\EtapeSaisie\EtapeSaisieDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\DroitComposant\CritereDroitComposantDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\DroitComposant\DroitComposantDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\DroitComposantController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\DroitComposant\DroitComposantMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\DroitComposant\DroitComposantMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\DroitComposant\DroitComposantDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\DroitComposant\DroitComposantDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\DroitComposant\DroitComposantConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\DroitComposantException\DroitComposantException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\DroitComposant\CritereDroitComposantDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\DroitComposant\DroitComposantDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Docligne\CritereDocligneDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Docligne\DocligneDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\DocligneController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Docligne\DocligneMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Docligne\DocligneMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Docligne\DocligneDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Docligne\DocligneDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Docligne\DocligneConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\DocligneException\DocligneException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Docligne\CritereDocligneDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Docligne\DocligneDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Docentete\CritereDocenteteDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Docentete\DocenteteDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\DocenteteController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Docentete\DocenteteMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Docentete\DocenteteMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Docentete\DocenteteDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Docentete\DocenteteDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Docentete\DocenteteConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\DocenteteException\DocenteteException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Docentete\CritereDocenteteDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Docentete\DocenteteDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\DemandeExport\CritereDemandeExportDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\DemandeExport\DemandeExportDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\DemandeExportController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\DemandeExport\DemandeExportMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\DemandeExport\DemandeExportMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\DemandeExport\DemandeExportDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\DemandeExport\DemandeExportDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\DemandeExport\DemandeExportConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\DemandeExportException\DemandeExportException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\DemandeExport\CritereDemandeExportDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\DemandeExport\DemandeExportDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Compteg\CritereComptegDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Compteg\ComptegDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ComptegController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Compteg\ComptegMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Compteg\ComptegMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Compteg\ComptegDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Compteg\ComptegDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Compteg\ComptegConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ComptegException\ComptegException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Compteg\CritereComptegDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Compteg\ComptegDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Composant\CritereComposantDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Composant\ComposantDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\ComposantController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Composant\ComposantMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Composant\ComposantMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Composant\ComposantDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Composant\ComposantDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Composant\ComposantConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\ComposantException\ComposantException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Composant\CritereComposantDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Composant\ComposantDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Banque\CritereBanqueDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Scripts\DTO\Banque\BanqueDTO.ts
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.SCA\Controllers\BanqueController.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDomain\Metier\Banque\BanqueMetierTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DomainLibrary\Metier\Banque\BanqueMetier.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\UnitTestDAL\Entities\Banque\BanqueDALTest.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Banque\BanqueDAL.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DataAccessLayer\Entities\Banque\BanqueConfiguration.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Exception\BanqueException\BanqueException.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Banque\CritereBanqueDTO.cs
// C:\Users\ylouis\Documents\01 - Projet Exo-Partners\SCA -ASP.NET\SCA.DTOLibrary\Entities\Banque\BanqueDTO.cs
